[package]
name = "auto-apply"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.45.1", features = ["full"] }
fantoccini = "0.21.5"
thirtyfour = "0.35.0"
undetected-chromedriver = "0.1.2"


